### PR TITLE
Introduction of consumer vs. build time POMs

### LINKED ISSUE #137: [Task] Ease grasp of SDK's metadata and dependencies from Maven POMs
Default `pom.xml` contain a lot of stuff which is only relevant for building and releasing the final artifact. However as a consuming developer of the SDK who is only using pre-build and released artifacts from Maven Central I'm mainly interested in the dependency and metadata section, i.e not how it's actual build in detail. Hence a more streamlined released POM without all the bells and whistles would help me best to easily spot what's relevant to me as consumer of the SDK.   

[Maven 5](https://cwiki.apache.org/confluence/display/MAVEN/POM+Model+Version+5.0.0#POMModelVersion5.0.0-Background) already decided to go down this road as well by separating between build time config and the actual released content. So the idea is not totally new and will become mainstream in a couple of years

### PR DESCRIPTION
**Pull request by schabdo**
Resolves #137

Not sure whether or not it make sense to flatten the POM of the CLI, too. I'm up for discussion and happily awaiting your feedback on that. So I leave it up to the reviewer ...

### CODE REVIEW

**Comment by atextor** [comment]
@schabdo Does it make sense to document the intent and location of the flattened pom? Or is this something self-explanatory for everyone who might be interested?

**Comment by schabdo** [comment]
If you agree I'd add a comment right above the plugin execution to shed some light on the intention and what's going on there. For consumer side I wouldn't mention/document anything since it's completely transparent

**Comment by atextor** [comment]
@schabdo This sounds sensible, please go ahead :)

**Comment by schabdo** [comment]
done

**Pull request merged**
